# -------------------------------------------------------------------------
# This is the spack configuration file, CONFIGURED for wp11 on llnl.cs.rice.edu
# Keys that are identical to the defaults have been omitted.
# Make sure to run bin/spacklink!
# -------------------------------------------------------------------------
config:
  # This is the path to the root of the Spack install tree.
  install_tree: /home/wp11/hpctoolkit-develop/install


  # Temporary locations Spack can try to use for builds.
  build_stage:
    - $tempdir/$user/spack-stage


  # The maximum number of jobs to use for the build system (e.g. `make`), when
  # the -j flag is not given on the command line. Defaults to 16 when not set.
  build_jobs: 20


  # How long to wait to lock the Spack installation database. This lock is used
  # when Spack needs to manage its own package metadata and all operations are
  # expected to complete within the default time limit. The timeout should
  # therefore generally be left untouched.
  db_lock_timeout: 120
