###   CUSTOMIZED for msi3 on gpu.cs
##
################################################################################
#                                                                              # 
# Local config settings to customize this HPCTest installation.                #
# They override the builtin settings in
#      internal/src/config-data/config-default.yaml                            #
# Edit as needed.                                                              #
#                                                                              #
################################################################################


profile:
  hpctoolkit:
    path: ~/bin/linux-rhel7-x86_64/gcc-7.3.0/hpctoolkit-develop-vg5tn2l7r4vyyegngrluidc2ug5jlmdo/

config:
#    batch:
#      manager: Slurm
#      default: false
#      params:
#        account:   commons
#        partition: commons
#        time:      "1:00:00"
run:
  ulimit:
    t: unlimited  # cpu time (seconds)
