#!/bin/sh

# script to set up the links in ~/gits/spack/etx/spack to install
#    on a <site> and <machine>
cd ~/gits/spack/etc/spack

if [ "$1" == "" ]; then
	echo "Site must be specified"
	exit 1
fi
if [ "$2" == "" ]; then
	echo "Machine must be specified"
	exit 1
fi
echo "Linking site $1 machine $2 for spack builds"

/bin/rm -rf *.yaml

ln  -s ~/gits/spack-configs/$1/$2/$2.config.yaml config.yaml
ln  -s ~/gits/spack-configs/$1/$2/$2.modules.yaml modules.yaml
ln  -s ~/gits/spack-configs/$1/$2/$2.packages.yaml packages.yaml

