# -------------------------------------------------------------------------
# This is the per-spack-instance configuration file customized for
# Frontier (OLCF)
# Keys that are identical to the defaults have been omitted.
# Make sure to run bin/spacklink!
# -------------------------------------------------------------------------
config:
  # This is the path to the root of the Spack install tree.
  install_tree:
    root: /ccs/proj/ums023/.install/frontier/install
