# -------------------------------------------------------------------------
# This is the per-site-instance configuration file customized for OLCF
# Keys that are identical to the defaults have been omitted.
# Make sure to run bin/spacklink!
# -------------------------------------------------------------------------
config:
  # Temporary locations Spack can try to use for builds.
  # Use MEMBERWORK for best performance.
  build_stage:
    - ${MEMBERWORK}/ums023/spack/stage


  # How long to wait to lock the Spack installation database. This lock is used
  # when Spack needs to manage its own package metadata and all operations are
  # expected to complete within the default time limit. The timeout should
  # therefore generally be left untouched.
  db_lock_timeout: 120
