# -------------------------------------------------------------------------
# This is the per-spack-instance configuration file customized
# by wp11 for gpu.cs.rice.edu
# Keys that are identical to the defaults have been omitted.
# Make sure to run bin/spacklink!
# -------------------------------------------------------------------------
config:
  # This is the path to the root of the Spack install tree.
  install_tree: /projects/deploy/install


  # Temporary locations Spack can try to use for builds.
  build_stage:
    - $tempdir/wp11/spack/stage


  # The default number of jobs to use when running `make` in parallel.
  # If set to 4, for example, `spack install` will run `make -j4`.
  # If not set, all available cores are used by default.
  build_jobs: 18


  # How long to wait to lock the Spack installation database. This lock is used
  # when Spack needs to manage its own package metadata and all operations are
  # expected to complete within the default time limit. The timeout should
  # therefore generally be left untouched.
  db_lock_timeout: 120
